apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: brokerHPA

spec:
 scaleTargetRef:
   kind: Deployment
   name: grp15-tseis-swtdisp-brokerservice
 minReplicas: 3
 maxReplicas: 5
 targetCPUUtilizationPercentage: 85