version: '3'

services:
  rabbitmqservice:
    image: rabbitmq:3.8.16-management-alpine
    auth:
      username: guest
      password: guest
    container_name: rabbitmq
    volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
        - name: RABBITMQ_USERNAME
          value: admin
        - name: RABBITMQ_PASSWORD
          value: G84i8W1GKfilq4nW
        RABBITMQ_ERLANG_COOKIE: IDFRSSJFXFMWMBATZTZP
    ports:
        - 5672:5672
        - 15672:15672
  grp15-tseis-swtdisp-apiproxyservice:
    build: './ApiProxyService/ApiProxyService'
    image: lucifersuncle/grp15-tseis-swtdisp-apiproxyservice
    labels:
      kompose.service.type: LoadBalancer
  grp15-tseis-swtdisp-brokerservice:
    build: './BrokerService'
    image: lucifersuncle/grp15-tseis-swtdisp-brokerservice
  grp15-tseis-swtdisp-providerservice:
    build: './ProviderService'
    image: lucifersuncle/grp15-tseis-swtdisp-providerservice
  grp15-tseis-swtdisp-shareownercontrol:
    build: './ShareOwnerControl'
    image: lucifersuncle/grp15-tseis-swtdisp-shareownercontrol
  grp15-tseis-swtdisp-shareservice:
    build: './ShareService'
    image: lucifersuncle/grp15-tseis-swtdisp-shareservice
  grp15-tseis-swtdisp-stocktraderbroker:
    build: './StockTraderBroker/StockTraderBroker'
    image: lucifersuncle/grp15-tseis-swtdisp-stocktraderbroker
  grp15-tseis-swtdisp-tobintaxservice:
    build: './TobinTaxService'
    image: lucifersuncle/grp15-tseis-swtdisp-tobintaxservice
  grp15-tseis-swtdisp-traderservice:
    build: './TraderService'
    image: lucifersuncle/grp15-tseis-swtdisp-traderservice
  grp15-tseis-swtdisp-requesterservice:
    build: './RequesterService'
    image: lucifersuncle/grp15-tseis-swtdisp-requesterservice    