apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: grp15-tseis-swtdisp-tobintaxservice
  name: grp15-tseis-swtdisp-tobintaxservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grp15-tseis-swtdisp-tobintaxservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: grp15-tseis-swtdisp-tobintaxservice
    spec:
      containers:
        - image: lucifersuncle/grp15-tseis-swtdisp-tobintaxservice
          name: grp15-tseis-swtdisp-tobintaxservice
          resources: {}
      restartPolicy: Always
status: {}
