apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 0.7.0 (c25b7e8)
  creationTimestamp: null
  labels:
    io.kompose.service: grp15-tseis-swtdisp-shareservice
  name: grp15-tseis-swtdisp-shareservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grp15-tseis-swtdisp-shareservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 0.7.0 (c25b7e8)
      creationTimestamp: null
      labels:
        io.kompose.service: grp15-tseis-swtdisp-shareservice
    spec:
      containers:
      - image: lucifersuncle/grp15-tseis-swtdisp-shareservice
        imagePullPolicy: ""
        name: grp15-tseis-swtdisp-shareservice
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
